// Тексты интерфейса: основной — татарский, подстрочник — русский или английский.
export type Line = { tt: string; ru: string; en: string };

export const S = {
  navLearn: { tt: "Өйрәнү", ru: "Обучение", en: "Learn" },
  navProgress: { tt: "Уңышлар", ru: "Прогресс", en: "Progress" },
  navSections: { tt: "Бүлекләр", ru: "Разделы", en: "Sections" },
  heroTitle: { tt: "Туган телне бергә өйрәник", ru: "Давайте вместе учить родной язык", en: "Let's learn our native language together" },
  heroLead: {
    tt: "Көненә биш минут: сүзләр, фразалар, диалоглар — тавыш белән.",
    ru: "Пять минут в день: слова, фразы и диалоги с озвучкой.",
    en: "Five minutes a day: words, phrases and dialogues with audio.",
  },
  ctaStart: { tt: "Өйрәнә башлау", ru: "Начать учить", en: "Start learning" },
  ctaBot: { tt: "Telegram-бот", ru: "Бот в Telegram", en: "Telegram bot" },
  counter: { tt: "сүз өйрәнелде", ru: "слов выучено", en: "words learned" },
  counterHint: { tt: "сезнең прогресс — бу җиһазда", ru: "ваш прогресс — на этом устройстве", en: "your progress on this device" },
  howTitle: { tt: "Ничек эшли", ru: "Как это работает", en: "How it works" },
  step1: { tt: "Сүзләр", ru: "Слова", en: "Words" },
  step1d: { tt: "Иң кирәкле сүзләрне тыңлап ятлыйсыз", ru: "Запоминаете самые нужные слова на слух", en: "Memorise the most useful words by ear" },
  step2: { tt: "Фразалар", ru: "Фразы", en: "Phrases" },
  step2d: { tt: "Сүзләрдән тормыштагы җөмләләр төзисез", ru: "Собираете из слов фразы для жизни", en: "Build everyday phrases from words" },
  step3: { tt: "Диалоглар", ru: "Диалоги", en: "Dialogues" },
  step3d: { tt: "Кибеттә, гаиләдә, урамда сөйләшәсез", ru: "Говорите в магазине, в семье, на улице", en: "Talk at the shop, at home, in the street" },
  demoTitle: { tt: "Беренче дәрес", ru: "Первый урок", en: "First lesson" },
  demoLead: { tt: "Карточканы әйләндерегез, тыңлагыз һәм кабатлагыз", ru: "Переверните карточку, послушайте и повторите", en: "Flip the card, listen and repeat" },
  flip: { tt: "Әйләндерү", ru: "Перевернуть", en: "Flip" },
  listen: { tt: "Тыңлау", ru: "Слушать", en: "Listen" },
  speak: { tt: "Әйтеп карау", ru: "Проверить произношение", en: "Check pronunciation" },
  listening: { tt: "Тыңлыйм…", ru: "Слушаю…", en: "Listening…" },
  pronGood: { tt: "Бик яхшы!", ru: "Отлично!", en: "Great!" },
  pronTry: { tt: "Тагын бер тапкыр", ru: "Попробуйте ещё раз", en: "Try once more" },
  pronSelf: { tt: "Дөрес әйттем", ru: "Я сказал(а) правильно", en: "I said it right" },
  pronUnsupported: {
    tt: "Браузер тавышны танымый — үзегез бәяләгез",
    ru: "Браузер не распознаёт речь — оцените себя сами",
    en: "Your browser can't recognise speech — rate yourself",
  },
  next: { tt: "Алга", ru: "Дальше", en: "Next" },
  prev: { tt: "Артка", ru: "Назад", en: "Back" },
  know: { tt: "Беләм", ru: "Знаю", en: "I know it" },
  done: { tt: "Дәрес тәмам! Булдырдыгыз!", ru: "Урок пройден! Вы молодец!", en: "Lesson complete! Well done!" },
  again: { tt: "Кабатлау", ru: "Повторить", en: "Repeat" },
  dashTitle: { tt: "Сезнең уңышлар", ru: "Ваш прогресс", en: "Your progress" },
  streak: { tt: "көн рәттән", ru: "дней подряд", en: "day streak" },
  learned: { tt: "өйрәнелгән сүз", ru: "выучено слов", en: "words learned" },
  lessons: { tt: "үткән дәрес", ru: "пройдено уроков", en: "lessons done" },
  activity: { tt: "Соңгы 14 көн", ru: "Активность за 14 дней", en: "Last 14 days" },
  sectionsTitle: { tt: "Бүлекләр", ru: "Разделы", en: "Sections" },
  alphabet: { tt: "Әлифба", ru: "Алфавит", en: "Alphabet" },
  alphabetD: { tt: "39 хәреф, татарча авазлар", ru: "39 букв и татарские звуки", en: "39 letters and Tatar sounds" },
  grammar: { tt: "Грамматика", ru: "Грамматика", en: "Grammar" },
  grammarD: { tt: "Сингармонизм, кушымчалар, килешләр", ru: "Сингармонизм, аффиксы, падежи", en: "Vowel harmony, suffixes, cases" },
  phrasebook: { tt: "Сөйләшмәлек", ru: "Разговорник", en: "Phrasebook" },
  phrasebookD: { tt: "Көндәлек сөйләм өчен фразалар", ru: "Фразы для повседневного общения", en: "Phrases for everyday talk" },
  listeningS: { tt: "Тыңлап аңлау", ru: "Аудирование", en: "Listening" },
  listeningD: { tt: "Тыңлагыз һәм дөрес җавапны сайлагыз", ru: "Слушайте и выбирайте верный ответ", en: "Listen and choose the right answer" },
  open: { tt: "Ачу", ru: "Открыть", en: "Open" },
  home: { tt: "Баш бит", ru: "Главная", en: "Home" },
  footerAbout: {
    tt: "Татар телен саклау һәм үстерү өчен түләүсез проект.",
    ru: "Бесплатный проект для сохранения и развития татарского языка.",
    en: "A free project to preserve and develop the Tatar language.",
  },
  footerContact: { tt: "Элемтә", ru: "Связь", en: "Contact" },
  footerLang: { tt: "Тел", ru: "Язык", en: "Language" },
  footerScript: { tt: "Язу", ru: "Письмо", en: "Script" },
  theme: { tt: "Төс темасы", ru: "Тема оформления", en: "Colour theme" },
  search: { tt: "Эзләү…", ru: "Поиск…", en: "Search…" },
  question: { tt: "Нәрсә ишеттегез?", ru: "Что вы услышали?", en: "What did you hear?" },
  score: { tt: "Нәтиҗә", ru: "Результат", en: "Score" },
  play: { tt: "Тыңлау", ru: "Прослушать", en: "Play" },
  start: { tt: "Башлау", ru: "Начать", en: "Start" },
  example: { tt: "Мисал", ru: "Пример", en: "Example" },
  alphabetLead: { tt: "Татар әлифбасында 39 хәреф. Алтысы — татар теленә генә хас авазлар.", ru: "В татарском алфавите 39 букв. Шесть из них передают особые татарские звуки.", en: "The Tatar alphabet has 39 letters. Six of them stand for sounds unique to Tatar." },
  grammarLead: { tt: "Иң кирәкле кагыйдәләр — кыска һәм мисаллар белән.", ru: "Самые нужные правила — коротко и с примерами.", en: "The most useful rules — short and with examples." },
  phrasebookLead: { tt: "Фразаны басыгыз — тыңлагыз һәм кабатлагыз.", ru: "Нажмите на фразу — послушайте и повторите.", en: "Tap a phrase — listen and repeat." },
  listeningLead: { tt: "Сүзне тыңлагыз һәм ишеткәнегезне сайлагыз.", ru: "Послушайте слово и выберите, что услышали.", en: "Listen to the word and choose what you heard." },
  special: { tt: "Татар авазы", ru: "Особый татарский звук", en: "Unique Tatar sound" },
  allTopics: { tt: "Барысы", ru: "Все", en: "All" },
  correct: { tt: "Дөрес!", ru: "Верно!", en: "Correct!" },
  wrong: { tt: "Ялгыш", ru: "Ошибка", en: "Wrong" },
} satisfies Record<string, Line>;

export type Key = keyof typeof S;
